apiVersion: v1
kind: Service
metadata:
  name: location-service
  labels:
    app: location-service
spec:
  ports:
  - port: 9004
    protocol: TCP
  clusterIP: None
  selector:
    app: location-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  labels:
    app: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
      - name: location-service
        image: location-service
