server:
  port: 9296

spring:
  main:
    show-banner: false
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thearchermancoding/config-server
          clone-on-start: true
    kubernetes:
      discovery:
        service-name: cloud-config-server