management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9000
spring:
  main:
    show-banner: false
  application:
    name: cloud-gateway
  cloud:
    config:
      enabled: false
    kubernetes:
      discovery:
        service-name: cloud-gateway
    gateway:
      discovery:
        locator:
          enabled: true