apiVersion: v1
kind: Service
metadata:
  name: store-service
  labels:
    app: store-service
spec:
  ports:
  - port: 9009
    protocol: TCP
  clusterIP: None
  selector:
    app: store-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service
  labels:
    app: store-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-service
  template:
    metadata:
      labels:
        app: store-service
    spec:
      containers:
      - name: store-service
        image: store-service
