server:
  port: 9001
spring:
  main:
    show-banner: false
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:h2:mem:employeedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  cloud:
    config:
      enabled: false
    kubernetes:
      discovery:
        service-name: employee-service
      reload:
        enabled: true
management:
  endpoint:
    restart:
      enabled: true