apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server
  labels:
    app: cloud-config-server
spec:
  ports:
  - port: 9296
    protocol: TCP
  clusterIP: None
  selector:
    app: cloud-config-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server
  labels:
    app: cloud-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-server
  template:
    metadata:
      labels:
        app: cloud-config-server
    spec:
      containers:
      - name: cloud-config-server
        image: cloud-config-server
