apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway
  labels:
    app: cloud-gateway
spec:
  ports:
  - port: 9000
    protocol: TCP
  clusterIP: None
  selector:
    app: cloud-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
  labels:
    app: cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway
  template:
    metadata:
      labels:
        app: cloud-gateway
    spec:
      containers:
      - name: cloud-gateway
        image: cloud-gateway
